---
Metadata:
  TemplateId: "arn:aws:cloudformation:us-east-1:211125738014:generatedTemplate/b6a0fb7c-2188-448c-ac96-8e228035d9ba"
Resources:

# IAM Policy for accessing CodeArtifact
  IAMManagedPolicy00policycodeartifactnuma501stconsumerpolicy00ciz43:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00numa501stservicerole00f8tKx"
    Properties:
      ManagedPolicyName: "codeartifact-numa501st-consumer-policy"
      Path: "/"
      Description: "Provides permissions to read from CodeArtifact."
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: "*"
          Action:
          - "codeartifact:GetAuthorizationToken"
          - "codeartifact:GetRepositoryEndpoint"
          - "codeartifact:ReadFromRepository"
          Effect: "Allow"
        - Condition:
            StringEquals:
              sts:AWSServiceName: "codeartifact.amazonaws.com"
          Resource: "*"
          Action: "sts:GetServiceBearerToken"
          Effect: "Allow"
      Roles:
      - "numa501st-servicerole"
      Users: []

 # IAM Policy for CodeBuild basic permissions     
  IAMManagedPolicy00policyserviceroleCodeBuildBasePolicynuma501stserviceroleuseast100YlXVi:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00numa501stservicerole00f8tKx"
    Properties:
      ManagedPolicyName: "CodeBuildBasePolicy-numa501st-servicerole-us-east-1"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - "arn:aws:logs:us-east-1:211125738014:log-group:/aws/codebuild/numa501st-web-build"
          - "arn:aws:logs:us-east-1:211125738014:log-group:/aws/codebuild/numa501st-web-build:*"
          Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Effect: "Allow"
        - Resource:
          - "arn:aws:s3:::codepipeline-us-east-1-*"
          Action:
          - "s3:PutObject"
          - "s3:GetObject"
          - "s3:GetObjectVersion"
          - "s3:GetBucketAcl"
          - "s3:GetBucketLocation"
          Effect: "Allow"
        - Resource:
          - "arn:aws:codecommit:us-east-1:211125738014:numa501st-web-project"
          Action:
          - "codecommit:GitPull"
          Effect: "Allow"
        - Resource:
          - "arn:aws:s3:::numa501st-build-artifacts-numa501st"
          - "arn:aws:s3:::numa501st-build-artifacts-numa501st/*"
          Action:
          - "s3:PutObject"
          - "s3:GetBucketAcl"
          - "s3:GetBucketLocation"
          Effect: "Allow"
        - Resource:
          - "arn:aws:codebuild:us-east-1:211125738014:report-group/numa501st-web-build-*"
          Action:
          - "codebuild:CreateReportGroup"
          - "codebuild:CreateReport"
          - "codebuild:UpdateReport"
          - "codebuild:BatchPutTestCases"
          - "codebuild:BatchPutCodeCoverages"
          Effect: "Allow"
      Roles:
      - "numa501st-servicerole"
      Users: []

# IAM Policy for granting access to CloudWatch Logs
  IAMManagedPolicy00policyserviceroleCodeBuildCloudWatchLogsPolicynuma501stwebbuilduseast100MNvdt:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00numa501stservicerole00f8tKx"
    Properties:
      ManagedPolicyName: "CodeBuildCloudWatchLogsPolicy-numa501st-web-build-us-east-1"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - "arn:aws:logs:us-east-1:211125738014:log-group:numa501st-build-logs"
          - "arn:aws:logs:us-east-1:211125738014:log-group:numa501st-build-logs:*"
          Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Effect: "Allow"
      Roles:
      - "numa501st-servicerole"
      Users: []

# CodeArtifact Local Repository
  CodeArtifactRepository00repositorynuma501stmavencentralstore00y8H6a:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties:
      RepositoryName: "maven-central-store"
      Description: "Provides Maven artifacts from Maven Central Repository."
      ExternalConnections:
      - "public:maven-central"
      DomainName:
        Fn::GetAtt:
        - "CodeArtifactDomain00domainnuma501st00HWLZM"
        - "Name"

# S3 bucket
  S3Bucket00numa501stbuildartifactsnuma501st00IX9O9:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    DependsOn: "IAMRole00numa501stservicerole00f8tKx"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "numa501st-build-artifacts-numa501st"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"

# CodeArtifact upstream Repository
  CodeArtifactRepository00repositorynuma501stnuma501stpackages00jg4mC:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties:
      Upstreams:
      - Fn::GetAtt:
        - "CodeArtifactRepository00repositorynuma501stmavencentralstore00y8H6a"
        - "Name"
      RepositoryName: "numa501st-packages"
      Description: "Packages for the web app."
      DomainName:
        Fn::GetAtt:
        - "CodeArtifactDomain00domainnuma501st00HWLZM"
        - "Name"

# CodeArtifact Domain
  CodeArtifactDomain00domainnuma501st00HWLZM:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Domain"
    DeletionPolicy: "Delete"
    Properties:
      DomainName: "numa501st"


 # CodeBuild service role     
  IAMRole00numa501stservicerole00f8tKx:           
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Delete"
    Properties:
      Path: "/service-role/"
      MaxSessionDuration: 3600
      RoleName: "numa501st-servicerole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "codebuild.amazonaws.com"


# CodeCommit Repository
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: numa501st-web-project
      RepositoryDescription: A web application for the numa501st home page

# CodeBuild Project
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: numa501st-web-build
      Description: Build project for numa501st web application
      Source:
        Type: CODECOMMIT
        Location: !GetAtt CodeCommitRepository.CloneUrlHttp
        BuildSpec: buildspec.yml
      Artifacts:
        Type: S3
        Name: numa501st-web-build.zip
        Packaging: ZIP
        Location: !Ref S3Bucket00numa501stbuildartifactsnuma501st00IX9O9
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:corretto8
      ServiceRole: !GetAtt IAMRole00numa501stservicerole00f8tKx.Arn
      LogsConfig:
        CloudWatchLogs:
          GroupName: numa501st-build-logs
          Status: ENABLED
          StreamName: webapp